version: 1.0.{build}

image: Visual Studio 2017

platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: VierGewinnt.sln
  verbosity: normal

  test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\VierGewinnt.Core.Tests\bin\Debug\netcoreapp2.2\VierGewinnt.Core.Tests.dll.dll -noshadow" -output:".\MyProject_coverage.xml"
- codecov -f "MyProject_coverage.xml
