version: 1.0.{build}
image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
#- choco install xunit.runner.console

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
   

build:
  project: VierGewinnt.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\VierGewinnt\VierGewinnt.Core.Tests\bin\Debug\netcoreapp2.0\VierGewinnt.Core.Tests.dll -noshadow" -filter:"+[VierGewinnt.Core*]* -[VierGewinnt.View.WPF*]*" -output:".\MyProject_coverage.xml"
- codecov -f "MyProject_coverage.xml
