version: 1.0.{build}
image: Visual Studio 2017

assembly_info:
 patch: true
 file: AssemblyInfo.cs
 assembly_version: '{version}'
 assembly_file_version: '{version}'
 assembly_informational_version: '{version}-rc1'
 
before_build:
- nuget restore
#- choco install opencover.portable
#- choco install codecov
 

#build:
#  project: VierGewinnt.sln
#  verbosity: minimal

build_script:
 - msbuild /verbosity:quiet "VierGewinnt"

test_script:
- OpenCover\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:" .\viergewinnt\VierGewinnt.Core.Tests\bin\Debug\netcoreapp2.2\VierGewinnt.Core.Tests.dll -noshadow" -filter:"+[VierGewinnt.Core*]* -[VierGewinnt.View.WPF*]*" -output:".\MyProject_coverage.xml"

after_test:
- codecov -f "MyProject_coverage.xml
