version: 1.0.{build}

branches:
  only:
  - master

image: Visual Studio 2019

platform: Any CPU

assembly_info:

  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- nuget restore
- choco install dotnetcore-sdk
- choco install codecov

build:
  project: VierGewinnt.sln
  verbosity: normal

test_script:
- OpenCover.Console.exe -register:administrator -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[VierGewinnt*]*" -output:".\MyProject_coverage.xml" -oldstyle

- codecov -f ".\MyProject_coverage.xml"
