version: 1.0.{build}
image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

- ps: cd..
- ps: cd..
- ps: dir
- ps: cd Tools
- ps: dir
- ps: cd..
- ps: cd User



assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'
   

build:
  project: VierGewinnt.sln
  verbosity: minimal

test_script:
- OpenCover\OpenCover.Console.exe -register:user -target:".\packages\xunit.runner.console\2.4.1\tools\net472\xunit.console.exe" -targetargs:"C:\projects\viergewinnt\VierGewinnt.Core.Tests\bin\Debug\netcoreapp2.2\VierGewinnt.Core.Tests.dll -noshadow" -filter:"+[VierGewinnt.Core*]* -[VierGewinnt.View.WPF*]*" -output:".\MyProject_coverage.xml"

- codecov -f "MyProject_coverage.xml
