version: 1.0.{build}
image: Visual Studio 2017

before_build:
- nuget restore
- nuget install OpenCover -OutputDirectory packages -Version 4.6.519
- nuget install Codecov -OutputDirectory packages -Version 1.3.0
- nuget install xunit.runner.console -OutputDirectory packages -Version 2.4.1


build:
  project: VierGewinnt.sln
  verbosity: minimal

test_script:
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\xunit.runner.console.2.4.1\tools\netcoreapp2.2\xunit.console.x86.exe" -targetargs:".\VierGewinnt.Core.Tests\bin\Debug\netcoreapp2.2\VierGewinnt.Core.Tests.dll -noshadow" -output:".\MyProject_coverage.xml"

#upload report
- .\packages\Codecov.1.3.0\tools\codecov.exe -f "MyProject_coverage.xml"