version: 1.0.{build}
image: Visual Studio 2017

assembly_info:
 patch: true
 file: AssemblyInfo.cs
 assembly_version: '{version}'
 assembly_file_version: '{version}'
 assembly_informational_version: '{version}-rc1'
 
before_build:
- nuget restore

build:
 project: VierGewinnt.sln
 verbosity: minimal
