version: 1.0.{build}
image: Visual Studio 2019 Preview 

# clone directory
clone_folder: c:\projects\VierGewinnt

before_build:
- nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

environment:
  COVERALLS_REPO_TOKEN: wV0xF9MgItkjVLSQjlM9ucsM6vBHL59m0   

build:
  project: VierGewinnt.sln

test_script:
- nuget install xunit.runner.console -OutputDirectory packages -Version 2.3.1
    
- nuget install OpenCover -OutputDirectory packages -Version 4.6.166

- dotnet tool install coveralls.net --version 1.0.0-beta0002 --tool-path tools

    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:dotnet.exe "-targetargs:"".\packages\xunit.runner.console.2.3.1\tools\netcoreapp2.0\xunit.console.dll"" "".\VierGewinnt\VierGewinnt.Core.Tests\bin\Debug\netcoreapp2.2\VierGewinnt.Core.Tests.dll"" -noshadow -appveyor" -filter:"+[VierGewinnt*]*" -oldStyle -output:opencoverCoverage.xml

    $coveralls = ".\tools\csmacnz.coveralls.exe"

   & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID